### PR TITLE
DicomPixelData.Create should not throw on BitsAllocated >= 16 if uncompressed.

### LINKED ISSUE #716: Creating of DicomPixelData with 32Bit not working in 4.x
I updated  from v3.0.2 to v4.0.0-rc1. 

### Expected behavior

Calling DicomDataPixel.Create(...) with BitsAllocated set to 32-bit not throwing an exception, works in v3.0.2
 
### Actual behavior

Now an exception is thrown when calling DicomDataPixel.Create(...):
Dicom.Imaging.DicomImagingException : Cannot represent pixel data with Bits Allocated: 32 > 16
   at Dicom.Imaging.DicomPixelData.Create(DicomDataset dataset, Boolean newPixelData) in C:\fo-dicom\DICOM\Imaging\DicomPixelData.cs:line 294

BitsAllocated, BitsStored, HighBit, SamplesPerPixel, Columns, Rows were set before calling DicomDataPixel.Create(...) by adding them to the DicomDataSet passed to Create(...) method.

### fo-dicom version and OS/platform

update from v3.0.2 to v4.0.0-rc1, Windows 10

Any suggestions?

### PR DESCRIPTION
**Pull request by mia-san**
Fixes #716.

#### Checklist
- [X] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [X] I have included unit tests
- [X] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- DICOM 3.5 A.2 says PixelData should have VR=OW when BitsAllocated > 8.
- still throws exception on BitsAllocated > 16 if PixelData is compressed(JPEG etc), perhaps due to native code's limitation.

### CODE REVIEW

**Comment by JuergenDick** [comment]
Info: I'm  currently  evaluating the new code.

**Comment by JuergenDick** [comment]
OK, all my tests are working well. 

HINT: The unit tests could not be compiled.

<Unit Tests>\<DICOM.Tests.NetCore> (3 items)
    Dicom (3 items)
      Error CS0117: "Encoding" enthÃ¤lt keine Definition fÃ¼r "Default". (500, 34)
      Error CS0117: "Encoding" enthÃ¤lt keine Definition fÃ¼r "Default". (515, 34)
      Error CS0117: "Encoding" enthÃ¤lt keine Definition fÃ¼r "Default". (530, 34)

**Comment by mia-san** [comment]
thank you for testing.
good to hear things are working for you.

regarding to compile error, which file the error comes from ?
what about your environment ?
at least, my VS2017 compiles without error.

**Comment by JuergenDick** [comment]
Hi,
the failed tests are in:
\Tests\Desktop\DicomDatasetTest.cs
Error CS0117: "Encoding" enthÃ¤lt keine Definition fÃ¼r "Default". (500, 34)
Error CS0117: "Encoding" enthÃ¤lt keine Definition fÃ¼r "Default". (515, 34)
Error CS0117: "Encoding" enthÃ¤lt keine Definition fÃ¼r "Default". (530, 34)

I think the problem is, that the same test code is used in different scenarios - Desktop and .Net Core. 

image

I use VS 2017 15.9.5

**Comment by mia-san** [comment]
um, System.Text.Encoding.Default seems to be available since .net standard 2.0, where as our '.NetCore' project is targeted to netstandard1.3.
I have .netcore 2.1 installed, probably that's why I don't see those errors.
will be revised later...

btw, if you comment out those unit tests, other unit tests succeeds?

**Comment by mia-san** [comment]
thank you for test results.
looks not that bad, but revise those failing tests some time later.

now I'll leave this pull-request to project owner, as those failing unit tests are rather off-topic.

thank you again for co-operations :)

**Comment by JuergenDick** [comment]
Thank you for evaluating and fixing.

**Comment by gofal** [comment]
Thanks!
Will fix the pull request by compiler condition to use ```Èncoding.Default``` in case of Desktop or netstandard2.0, and ```Encoding.GetEncoding(0)```, which also returns the default encoding of the environment, in other cases.
This will keep fo-dicom portable.
